modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/wake-up-time/issues"

[[mods]]
modId = "wake_up_time"
version = "${file.jarVersion}"
displayName = "Wake Up Time"
displayURL="https://github.com/JamCoreModding/wake-up-time"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Figure out what stage of the day your villagers are in
'''

[[dependencies.wake_up_time]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "jamlib"
mandatory = true
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
