modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/wake-up-time/issues"

[[mods]]
modId = "wake_up_time"
version = "${file.jarVersion}"
displayName = "Wake Up Time"
displayURL="https://github.com/JamCoreModding/wake-up-time"
logoFile = "icon.png"
authors = "Jamalam, triphora"
description = '''
Figure out what stage of the day your villagers are in
'''

[[dependencies.wake_up_time]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wake_up_time]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
